" Must be first line
set nocompatible

" Binds Control+s to save
map <C-s> :w<cr>

" Binds Al+q to save and quit
map <M-q> :wq<cr>

" Binds F6 to Nerdtree
nmap <F6> :NERDTreeToggle<CR>

" Binds Control-l to redraw screen and remove highlights
nnoremap <silent> <C-l> :nohl<CR><C-l>

" Sources a plugin file
if filereadable(expand("~/.vimrc.plug"))
	source ~/.vimrc.plug
endif

" Remaps Tab to choose suggestion Coc
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

" Forgot what this does, but I know it's something important
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Inserts suggested text when Enter is placed Coc
if exists('*complete_info')
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
else
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
endif

" Spell checking
set spell spelllang=en_us

" Convert tabs to spaces
set expandtab

" Automatically indent lines
set autoindent

" Set tab to 4 spaces
set tabstop=4

" Set tab to 4 spaces
set shiftwidth=4

" Disable automatic file detection
filetype off

" Make backspace key work
set backspace=indent,eol,start

" Sets up Vundle for extensions
set rtp+=~/.vim/bundle/Vundle.vim

" Sets cursor to a vertical line
set guicursor=v-r-i:ver25

" Sets cursor to underline when in normal mode
set guicursor=n:hor25

" Syntax color highlighting
syntax on

" Wraps text
set wrap

" Fast scrolling
set ttyfast

" Slow redraw for better performance
set lazyredraw

" Always display status line
set laststatus=2

" Matches matching Greater and Less than signs
set matchpairs+=<:>

" Shows line numbers
set number

" Highlights matching search patterns
set hlsearch

" Plugin start
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'           " Vundle extension manager
Plugin 'neoclide/coc.nvim'              " Coc for code linting
Plugin 'wakatime/vim-wakatime'          " Wakatime for measuring how much time is spent in Vim
Plugin 'preservim/nerdtree'             " Nerdtree for viewing file tree
Plugin 'jiangmiao/auto-pairs'           " Auto-pairs automatically closes brackets
Plugin 'junegunn/fzf'                   " Fuzzy finder
Plugin 'ryanoasis/vim-devicons'         " Icons for Vim
Plugin 'vim-airline/vim-airline'        " Statusline for Vim
Plugin 'vim-airline/vim-airline-themes' " Themes for Vim-airline
Plugin 'thaerkh/vim-indentguides'       " Guides for indentation levels

" Plugin end
call vundle#end()

" Sources a plugin file
if filereadable(expand("~/.vimrc.plug"))
	source ~/.vimrc.plug
endif
