if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="/Users/Matei/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
git
zsh-autosuggestions
zsh-syntax-highlighting
z
sudo
wakatime
vscode
)

export EDITOR='nvim'

setopt hist_ignore_all_dups
setopt hist_reduce_blanks
setopt share_history
setopt correct_all

source $ZSH/oh-my-zsh.sh

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zshi
source /Users/Matei/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

alias iip='ipconfig getifaddr en1'
alias eip='curl ifconfig.me'
alias ql='qlmanage -p'
alias weather='ansiweather -l Dubai -a false -s true'
alias wolfram='wolframalpha'
alias pytop='bpytop'
alias pipes='pipes.sh'
alias clock='tty-clock -s'
alias timer='ttimer'
alias news='newsboat'
alias tron='ssh sshtron.zachlatta.com'
alias map='mapscii'
alias vlc='/Applications/VLC.app/Contents/MacOS/VLC --intf ncurses'
alias music='cmus'
alias virtualenv='python3 -m venv ./venv'
alias virtualact='source ./venv/bin/activate'
alias rm='trash'
alias temp='istats all'
alias :q='exit'
alias vim='nvim'
alias reddit='ttrv'
alias tmux-attach='tmux attach -t'
alias tmux-new='tmux new-session -s'
alias tmux-list='tmux list-sessions'
alias vimrc='vim ~/.vimrc'

export PATH="/usr/local/sbin:$PATH"
export BAT_THEME="Nord"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
